// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZO_XOSs4uBVS5o8-wKjBfsh1cbKbuTRA',
    appId: '1:1052807036864:web:08988c4bedd03394171225',
    messagingSenderId: '1052807036864',
    projectId: 'aqualert-c72a5',
    authDomain: 'aqualert-c72a5.firebaseapp.com',
    storageBucket: 'aqualert-c72a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJMzPjgx70dk4DSJaUvqniqYNzS9q-L0',
    appId: '1:1052807036864:android:f6e7693315e2aa8f171225',
    messagingSenderId: '1052807036864',
    projectId: 'aqualert-c72a5',
    storageBucket: 'aqualert-c72a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLZtzgubFwIZdUVOK8bsn6ivZmBF9KLw',
    appId: '1:1052807036864:ios:64d6db4671e6620b171225',
    messagingSenderId: '1052807036864',
    projectId: 'aqualert-c72a5',
    storageBucket: 'aqualert-c72a5.firebasestorage.app',
    iosBundleId: 'com.example.aqualertSmartwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLZtzgubFwIZdUVOK8bsn6ivZmBF9KLw',
    appId: '1:1052807036864:ios:64d6db4671e6620b171225',
    messagingSenderId: '1052807036864',
    projectId: 'aqualert-c72a5',
    storageBucket: 'aqualert-c72a5.firebasestorage.app',
    iosBundleId: 'com.example.aqualertSmartwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZO_XOSs4uBVS5o8-wKjBfsh1cbKbuTRA',
    appId: '1:1052807036864:web:43199f92cefb1250171225',
    messagingSenderId: '1052807036864',
    projectId: 'aqualert-c72a5',
    authDomain: 'aqualert-c72a5.firebaseapp.com',
    storageBucket: 'aqualert-c72a5.firebasestorage.app',
  );
}
